name: Publish
on:
  push:
    branches: [ "master" ]
    tags:
      - v*

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: npm install
        
      - name: Publish package
        run: npx jsr publish --allow-dirty

      
